# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_SPMV_wrappers", use_symbols = TRUE, package_name = "SPMV")

#' @usage NULL
#' @useDynLib SPMV, .registration = TRUE
NULL

sparse_matvec <- function(i, p, x, nrow, ncol, vec) .Call(wrap__sparse_matvec, i, p, x, nrow, ncol, vec)

sparse_matvec_direct <- function(i, p, x, nrow, ncol, vec) .Call(wrap__sparse_matvec_direct, i, p, x, nrow, ncol, vec)


# nolint end
